### ISSUE TITLE
debian-binary: Permission denied - Failed to extract deb

### ISSUE THREAD

**Issue by pokyah** [megamaced/spotify-easyrpm#1]
Hi !

thanks for sharing this script ! I'm not a linux advanced user and I can't make your script to work.

After downloading the deb package, the extraction step of your script does not work. 

I got to following error message : 

`FINISHED --2017-07-05 10:07:57--
Total wall clock time: 6m 24s
Downloaded: 3 files, 158M in 6m 24s (421 KB/s)
Checking if we downloaded multiple versions
Removing the older downloaded versions
Comparing downloaded version to installed version (if any)
Extracting deb and preparing for build
debian-binary: Permission denied
Failed to extract deb
`

Any idea of what can I do to make this step work ? 

Thanks for your help !

**Comment by megamaced** [comment]
Perhaps there is a deb in that location that is not owned by your user account (perhaps root)?

Perhaps delete any spotify*.deb out this folder:
/home/user/rpmbuild/SOURCES/

**Comment by Fabian188** [comment]
At least renaming /home/user/rpmbuild helped for me for this issue. Note that I have the outdated packman spotify version running.

**Comment by ryhaberecht** [comment]
The installer from packman puts stuff into /home/user/rpmbuild/ too.
Maybe the version check goes wrong, because packman's version starts with "0."
Or the current user has no permissions for that directory, usually because it was created by root.

**Comment by megamaced** [comment]
I can add something to the code to fix up what the packman spotify installer does. 

Is the main issue that the packman version creates $HOME/rpmbuild as root?

**Comment by megamaced** [comment]
I went and installed the packman version, ran their script and installed the old spotify 0.9.x version if gives. I then ran spotify-easyrpm and it didn't conflict. The RPM generated from easyrpm just upgraded the packman version.

In easyrpm v1.1.1 I added a check to ensure rpmbuild is owned by your user. I think that will resolve the main issue here of not being the owner

**Comment by Blinking6889** [comment]
Can confirm this works. Had an existing issue with libgcrypt11.so and a pre-existing spotify rpm in /home/$USER/rpmbuild likely from another installer script from OBS. Installed the official libgcrypt libraries from OBS and removed the entire rpmbuild directory. Everything installed as expected. Thanks for this, as the snap and flatpacks are currently broken in tumbleweed.
