### ISSUE TITLE
spotify expects libcurl-gnutls.so.4

### ISSUE THREAD

**Issue by hessg** [megamaced/spotify-easyrpm#22]
```
Loading repository data...
Reading installed packages...
Resolving package dependencies...


Problem: nothing provides libcurl-gnutls.so.4()(64bit) needed by spotify-client-1.1.5.153.gf614956d-16.x86_64
 Solution 1: do not install spotify-client-1.1.5.153.gf614956d-16.x86_64
 Solution 2: break spotify-client-1.1.5.153.gf614956d-16.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c
```

The script immediately chooses cancel.
I linked libcurl.so.4.5.0 to libcurl-gnutls.so.4 like suggested [here](https://flanaras.wordpress.com/2016/02/20/install-spotify-on-opensuse-leap-42-1/)

```
~> ls /usr/lib64/libcurl*                                                           10:01AM
lrwxrwxrwx 1 root root   16 May  7 10:01 /usr/lib64/libcurl-gnutls.so.4 -> libcurl.so.4.5.0
lrwxrwxrwx 1 root root   16 Apr 15 12:02 /usr/lib64/libcurl.so.4 -> libcurl.so.4.5.0
-rwxr-xr-x 1 root root 575K Apr 15 12:03 /usr/lib64/libcurl.so.4.5.0
```

**Comment by hessg** [comment]
I see you already have the linking in your code, that didn't work for me though, I had to link it manually.

**Comment by megamaced** [comment]
That's really odd that your local rpm build of spotify-client required libcurl-gnutls.so.4.

My rpm spec has this:
AutoReq:  no

Which should stop automatically detecting which libraries are linked against. And then as you discovered we do the symlinking as a %post step

Do you have some local configuration to override AutoReq: No ?

**Comment by hessg** [comment]
This was on a fresh openSUSE Tumbleweed installation.

`/usr/lib/rpm/find-requires` has only this one line:
```
#!/bin/sh

/usr/lib/rpm/rpmdeps --define="_use_internal_dependency_generator 1" --requires
```

and in `/home/<user>/rpmbuild/BUILD/spotify-client-1.1.5.153.gf614956d/find-requires.sh` there is
```
#!/bin/sh

/usr/lib/rpm/find-requires | \
     sed -e 's/lib\(nss3\|nssutil3\|smime3\|plc4\|nspr4\)\.so\.[01]d/lib\1.so/
             /lib\(curl\|crypto\|ssl\|gcrypt\)\.so/d'
```

No AutoReq in `/usr/lib/rpm/rpmrc` either. 
That should be overridden by the spec file anyway, no?

**Comment by megamaced** [comment]
what do you see if you check requires on the generated spotify-client rpm?

```
david@linux-z57y:/var/cache/spotify-easyrpm> rpm -qpR spotify-client-1.1.5.153.gf614956d-0.x86_64.rpm 
/bin/sh
/bin/sh
gconf2
libX11-6
libXtst6
libasound2
libatomic1
libcurl4
libgcrypt20
libglib-2_0-0
libgtk-2_0-0
libopenssl1_1
libudev1
mozilla-nss
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
xdg-utils
```

**Comment by hessg** [comment]
```
~> rpm -qpR /var/cache/spotify-easyrpm/spotify-client-1.1.5.153.gf614956d-0.x86_64.rpm                                                             10:52AM
/bin/sh
/bin/sh
gconf2
libX11-6
libXtst6
libasound2
libatomic1
libcurl4
libgcrypt20
libglib-2_0-0
libgtk-2_0-0
libopenssl1_1
libudev1
mozilla-nss
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
xdg-utils
```
exactly the same...
I built this rpm by copying your rpmbuild command and executing it from hand which really surprised me that it was working after failing in the script.

However I found the issue for me.
I had previously tried another installation method, [this one](https://github.com/flanaras/opensuse-spotify-installerl) I think, and had the .deb package I got from there in the same directory.
Looking at the requires of that rpm gives me quite a long list of requirements, including
```
~> rpm -qpR /var/cache/spotify-easyrpm/spotify-client-1.1.5.153.gf614956d-16.x86_64.rpm | grep gnu                                                 11:00AM
libcurl-gnutls.so.4()(64bit)
libcurl-gnutls.so.4(CURL_GNUTLS_3)(64bit)
```

The slightly different name (-16.x86_64.rpm) is in the initial issue message as well, I didn't notice that sorry.
At least it's no issue with your code as far as I can see.

If you agree on that, you can close the issue, sorry for the trouble.
