### ISSUE TITLE
Script ignores existing RPM build directory

### ISSUE THREAD

**Issue by phrxmd** [megamaced/spotify-easyrpm#32]
I have a custom RPM build directory in an `~/.rpmmacros` file, like this:
```
%_topdir /home/myusername/programming/rpmbuild
```

However, `spotify-easyrpm` ignores this and uses a hard-coded RPM build directory. It would be preferable if it would honor the existing system settings.

**Comment by ryhaberecht** [comment]
Could you please re-test?

**Comment by cbcoutinho** [comment]
Just tested this on 2.1.2, and on my system it respects a custom `%_topdir` in `~/.rpmmacros`

**Comment by megamaced** [comment]
fixed in 2.1.2
