### ISSUE TITLE
Update failed due to unsquashfs command missing, caused by missing dependency squashfs

### ISSUE THREAD

**Issue by sandersantema** [megamaced/spotify-easyrpm#42]
This wasn't installed on my system, possibly because I've removed everything snap related. But it might be nice to mention this in the readme non the less given that there's a higher chance that people who install this will probably not have snap stuff installed either.

**Comment by megamaced** [comment]
Hi

Did  you install spotify-easyrpm via RPM or by git cloning this repo and then running it?

Also do you know which version of easyrpm you were running? Version 3.0.0 was missing a check for unsquashfs but in version 3.0.1 this should be fixed:

```if ! rpm -q squashfs > /dev/null 2>&1; then
 echo "Installing build dependencies (squashfs)"
 if ! sudo zypper --non-interactive in squashfs; then
 f_error "Failed to install build dependencies (squashfs). Aborting"
 fi```

**Comment by sandersantema** [comment]
Ah I see, the culprit was probably running an older version from source I suppose it's solved now.
