### ISSUE TITLE
Unsupported architecture on x86

### ISSUE THREAD

**Issue by worldofgeese** [megamaced/spotify-easyrpm#48]
I have a Lenovo ThinkPad X1 Nano. On openSUSE Tumbleweed, invoking `spotfy-easyrpm` outputs `Unsupported architecture. Aborting
Please submit bug report to https://github.com/megamaced/spotify-easyrpm/issues`.

**Comment by megamaced** [comment]
@worldofgeese what is the output from

`uname -i`

**Comment by megamaced** [comment]
closing as no further info

**Comment by CYAXXX** [comment]
@megamaced 
> uname -i i386

its not supported on 32bit cpu's

**Comment by Umeaboy** [comment]
I see this for x86_64 as well, but uname -i weirdly says unknown as a reply.

uname -m proves that I have a x86_64 based machine:

[kristoffer@localhost]$ uname -m
x86_64

**Comment by Umeaboy** [comment]
I built using the 4.0.0-dev archive and it still says unsupported.
