### ISSUE TITLE
Failed to install build dependencies (update-desktop-files). Aborting

### ISSUE THREAD

**Issue by DeSchmiddi** [megamaced/spotify-easyrpm#51]
`Das folgende NEUE Paket wird installiert:
  update-desktop-files

1 neues Paket zu installieren.
Gesamtgröße des Downloads: 16,2 KiB. Bereits im Cache gespeichert: 0 B. Nach der Operation werden zusätzlich 17,4 KiB belegt.
Fortfahren? [j/n/v/...? zeigt alle Optionen] (j): j
Paket update-desktop-files-84.87-1.16.noarch abrufen                                                                                                                                                   (1/1),  16,2 KiB ( 17,4 KiB entpackt)
Abrufen: update-desktop-files-84.87-1.16.noarch.rpm ...................................................................................................................................................................[fertig (14,9 KiB/s)]

Überprüfung auf Dateikonflikte läuft: ..............................................................................................................................................................................................[fertig]
(1/1) Installieren: update-desktop-files-84.87-1.16.noarch .........................................................................................................................................................................[fertig]
Failed to install build dependencies (update-desktop-files). Aborting
Please submit bug report to https://github.com/megamaced/spotify-easyrpm/issues
`

**Comment by megamaced** [comment]
@DeSchmiddi is it available?

`zypper se --details update-desktop-files
Loading repository data...
Reading installed packages...

S | Name                 | Type    | Version   | Arch   | Repository
--+----------------------+---------+-----------+--------+----------------------
i | update-desktop-files | package | 84.87-5.6 | noarch | Main Repository (OSS)`

**Comment by megamaced** [comment]
can you install it manually?

zypper in update-desktop-files

**Comment by DeSchmiddi** [comment]
Sorry for takeing so long, I'll try at once

**Comment by DeSchmiddi** [comment]
Solved it, thanks, I feel so stupid
