### ISSUE TITLE
Directory /var/cache/spotify-easyrpm/ must exist

### ISSUE THREAD

**Issue by rufevean** [megamaced/spotify-easyrpm#61]
when am trying to remove the repo to reinstall it, its showing this error
```
MODE: clean-repo
CHANNEL: stable
[sudo] password for root: 
find: ‘/var/cache/spotify-easyrpm’: No such file or directory
Directory /var/cache/spotify-easyrpm/ must exist
Failed to create / update local repo. Aborting
Please submit bug report to https://github.com/megamaced/spotify-easyrpm/issues
```

**Comment by megamaced** [comment]
something has gone awry, try `--create-schedule` option to see if that fixes it all up

**Comment by armync** [comment]
@megamaced Same issue still exist, even for new installations

> Version: 3.0.5
> Spotify RPM tool for openSUSE / SLE
> SUPPORT: https://github.com/megamaced/spotify-easyrpm/issues
> 
> MODE: prompt
> CHANNEL: stable
> Creating build dirs in /home/user/rpmbuild
> find: ‘/var/cache/spotify-easyrpm’: No such file or directory
> Comparing snapcraft.io repo version to installed or local machine repo version (if any)
> Downloading the latest Spotify snap
> Extracting snap and preparing
> Parallel unsquashfs: Using 12 processors
> 319 inodes (3250 blocks) to write
> 
> [===========================================================================================|] 3569/3569 100%
> 
> created 234 files
> created 32 directories
> created 85 symlinks
> created 0 devices
> created 0 fifos
> created 0 sockets
> created 0 hardlinks
> Preparing RPM src tarball
> Writing new build file
> Running rpm build
> warning: Missing build-id in /home/user/rpmbuild/BUILDROOT/spotify-client-1.2.37.701.ge66eb7bc-0.x86_64/usr/share/spotify/spotify
> Spotify RPM created in /home/user/rpmbuild/RPMS/x86_64/
> Do you wish to install the Spotify RPM (y/n)?
