### ISSUE TITLE
Spotify app is not opening

### ISSUE THREAD

**Issue by nathan-lamy** [megamaced/spotify-easyrpm#65]
Hi !

I've installed spotify but after a few reboots it won't work anymore...
I had the same issue with the Flatpak version and this is why I switched.

I think this issue will be lacking some logs/reproducibility, don't hesitate to ask if you need anything more!

Quick list of what I tried :
- uninstalling/reinstalling
- deleting config
- using Flatpak version again (not opening too)
- searching on internet for similar issues

Logs of the issues :
```
rakox@localhost:~> spotify
spotify: /lib64/libcurl-gnutls.so.4: no version information available (required by spotify)
/usr/share/spotify/spotify: /lib64/libcurl-gnutls.so.4: no version information available (required by /usr/share/spotify/spotify)
/usr/share/spotify/spotify: /lib64/libcurl-gnutls.so.4: no version information available (required by /usr/share/spotify/spotify)
```
Nothing more in journalctl neither...

Thank you in advance :))

**Comment by vfred0** [comment]
Hi, I found this [solution](https://aur.archlinux.org/packages/spotify), initialize the window manager using dbus-run-session, for example I use Xorg: dbus-run-session startx. I hope it will be useful for you

**Comment by nathan-lamy** [comment]
Thank you for your reply !
I don't know how to start it properly, it won't work using dbus...
```
> dbus-run-session startplasma-x11
Plasma seems to be already running on this display.
```

**Comment by vfred0** [comment]
I did some research and you might find this solution useful: 
First in your DE press `CTRL + ALT + F3` and opened tty then  `killall plasmashell && killall kwin_x11` and then `dbus-run-session startplasma-x11`.

I don't know much about plasma

**Comment by nathan-lamy** [comment]
Nope :(
`CTRL + ALT + F3` just turns my entire screen black
And `killall plasmashell && killall kwin_x11`, kill my desktop so that behind the opened windows everything is black...
If I try to start plasma in dbus, I get the exact same error message...

**Comment by nathan-lamy** [comment]
And when I try to open Spotify, the taskbar shows a loading icon for like a few seconds and just stops, without any window opening :(

**Comment by vfred0** [comment]
Try with `CTRL+ALT+F2`. It looks something like this:
![image](https://github.com/megamaced/spotify-easyrpm/assets/86375181/46e10e08-9d71-44a7-9627-cae2a93a920f)

I hope you get the tty this time, bro

**Comment by nathan-lamy** [comment]
That was not working neither... only `F2` was resuming to my desktop
I switched to Gnome (X11) and get it working!
